function [ testData, fs ] = getData()
%GETDATA Summary of this function goes here
%   Detailed explanation goes here

    folder='E:\FH\Masterthesis\recordings\onset_detection';
    testFiles = {
        strcat(folder,'\play_bass_snare_off_171624.wav'), ...
        strcat(folder,'\play_crash_snare_off_172801.wav'), ...
        strcat(folder,'\play_hihat_open_snare_off_172631.wav'), ...
        strcat(folder,'\play_hihat_snare_off_172341.wav'), ...
        strcat(folder,'\play_ride_snare_off_172832.wav'), ...
        strcat(folder,'\play_snare_snare_off_172254.wav'), ...
        strcat(folder,'\play_tom1_snare_off_172455.wav'), ...
        strcat(folder,'\play_tom2_snare_off_172518.wav'), ...
        strcat(folder,'\play_tom3_snare_off_172540.wav'), ...
        strcat(folder,'\play_snare_off_173405_track35.wav'), ...
        strcat(folder,'\play_snare_off_173512_track36.wav'), ...
        strcat(folder,'\play_snare_off_173552_track37.wav'), ...
        strcat(folder,'\play_snare_off_173613_track38.wav'), ...
        strcat(folder,'\play_snare_off_173747_track39.wav'), ...
        strcat(folder,'\play_snare_off_174249_fillin_track53.wav'), ...
        strcat(folder,'\play_snare_off_174618_track59_1.wav'), ...
        strcat(folder,'\play_snare_off_174809_track59_2.wav'), ...
        strcat(folder,'\play_snare_off_175935_track80.wav'), ...
        strcat(folder,'\play_snare_off_180120_snare.wav'); ...
    };

    
    % build training data array
    % build training data array
    testData=cell(length(testFiles),1);
    for i=1:length(testFiles)
       [y,fs] = audioread(char(testFiles(i))); 
       testData{i} = y;
    end
    
end

