function [ training_drums, test_drums, training_data, test_data, fs ] = GetData2( folder )
%GETDATA Summary of this function goes here
%   Detailed explanation goes here

    training_files = {
        'crash', ...
        strcat(folder,'\play_crash_snare_on_141143.wav'), ...
        strcat(folder,'\play_crash_snare_on_141153.wav'), ...
        strcat(folder,'\play_crash_snare_on_141202.wav'), ...
        strcat(folder,'\play_crash_snare_on_141212.wav'), ...
        strcat(folder,'\play_crash_snare_on_141222.wav'), ...
        strcat(folder,'\play_crash_snare_on_141231.wav'), ...
        strcat(folder,'\play_crash_snare_on_141240.wav'), ...
        strcat(folder,'\play_crash_snare_on_141249.wav'), ...
        strcat(folder,'\play_crash_snare_on_141259.wav'), ...
        strcat(folder,'\play_crash_snare_on_141309.wav'); ...

        'ride', ...
        strcat(folder,'\play_ride_snare_on_141819.wav'), ...
        strcat(folder,'\play_ride_snare_on_141809.wav'), ...
        strcat(folder,'\play_ride_snare_on_141712.wav'), ...
        strcat(folder,'\play_ride_snare_on_141701.wav'), ...
        strcat(folder,'\play_ride_snare_on_141650.wav'), ...
        strcat(folder,'\play_ride_snare_on_141639.wav'), ...
        strcat(folder,'\play_ride_snare_on_141628.wav'), ...
        strcat(folder,'\play_ride_snare_on_141617.wav'), ...
        strcat(folder,'\play_ride_snare_on_141605.wav'), ...
        strcat(folder,'\play_ride_snare_on_141555.wav'); ...

        'hihat open', ...
        strcat(folder,'\play_hihat_open_snare_on_140116.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140106.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140055.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140040.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140029.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140019.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_140009.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135959.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135949.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135938.wav'); ...

        'hihat closed', ...
        strcat(folder,'\play_hihat_snare_on_135542.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135548.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135554.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135600.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135606.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135612.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135619.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135625.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135631.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135637.wav'); ...

        'bass', ...
        strcat(folder,'\play_bass_snare_off_134149.wav'), ...
        strcat(folder,'\play_bass_snare_off_134155.wav'), ...
        strcat(folder,'\play_bass_snare_off_134202.wav'), ...
        strcat(folder,'\play_bass_snare_off_134209.wav'), ...
        strcat(folder,'\play_bass_snare_off_134216.wav'), ...
        strcat(folder,'\play_bass_snare_off_134222.wav'), ...
        strcat(folder,'\play_bass_snare_off_134229.wav'), ...
        strcat(folder,'\play_bass_snare_off_134235.wav'), ...
        strcat(folder,'\play_bass_snare_off_134243.wav'), ...
        strcat(folder,'\play_bass_snare_off_134257.wav'); ...

        'snare', ...
        strcat(folder,'\play_snare_snare_on_134854.wav'), ...
        strcat(folder,'\play_snare_snare_on_134902.wav'), ...
        strcat(folder,'\play_snare_snare_on_134910.wav'), ...
        strcat(folder,'\play_snare_snare_on_134921.wav'), ...
        strcat(folder,'\play_snare_snare_on_134930.wav'), ...
        strcat(folder,'\play_snare_snare_on_134937.wav'), ...
        strcat(folder,'\play_snare_snare_on_134944.wav'), ...
        strcat(folder,'\play_snare_snare_on_134952.wav'), ...
        strcat(folder,'\play_snare_snare_on_135004.wav'), ...
        strcat(folder,'\play_snare_snare_on_135011.wav'); ...

        'tom 1', ...
        strcat(folder,'\play_tom1_snare_on_140312.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140327.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140333.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140341.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140348.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140355.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140401.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140407.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140414.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140421.wav'); ...

        'tom 2', ...
        strcat(folder,'\play_tom2_snare_on_140540.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140546.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140552.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140559.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140605.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140611.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140620.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140627.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140634.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140640.wav'); ...

        'tom 3', ...    
        strcat(folder,'\play_tom3_snare_on_140756.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140802.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140808.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140814.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140836.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140842.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140854.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140913.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140928.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140936.wav');
    };

    test_files = {
        'crash', ...
        strcat(folder,'\play_crash_snare_on_140957.wav'), ...
        strcat(folder,'\play_crash_snare_on_141022.wav'), ...
        strcat(folder,'\play_crash_snare_on_141032.wav'), ...
        strcat(folder,'\play_crash_snare_on_141041.wav'), ...
        strcat(folder,'\play_crash_snare_on_141050.wav'), ...
        strcat(folder,'\play_crash_snare_on_141059.wav'), ...
        strcat(folder,'\play_crash_snare_on_141108.wav'), ...
        strcat(folder,'\play_crash_snare_on_141118.wav'), ...
        strcat(folder,'\play_crash_snare_on_141127.wav'), ...
        strcat(folder,'\play_crash_snare_on_141135.wav'); ...

        'ride', ...
        strcat(folder,'\play_ride_snare_on_141352.wav'), ...
        strcat(folder,'\play_ride_snare_on_141406.wav'), ...
        strcat(folder,'\play_ride_snare_on_141418.wav'), ...
        strcat(folder,'\play_ride_snare_on_141435.wav'), ...
        strcat(folder,'\play_ride_snare_on_141449.wav'), ...
        strcat(folder,'\play_ride_snare_on_141501.wav'), ...
        strcat(folder,'\play_ride_snare_on_141514.wav'), ...
        strcat(folder,'\play_ride_snare_on_141524.wav'), ...
        strcat(folder,'\play_ride_snare_on_141534.wav'), ...
        strcat(folder,'\play_ride_snare_on_141544.wav'); ...

        'hihat open', ...
        strcat(folder,'\play_hihat_open_snare_on_135728.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135743.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135755.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135805.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135816.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135825.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135835.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135845.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135856.wav'), ...
        strcat(folder,'\play_hihat_open_snare_on_135907.wav'); ...

        'hihat closed', ...
        strcat(folder,'\play_hihat_snare_on_135410.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135422.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135447.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135452.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135508.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135514.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135520.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135525.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135531.wav'), ...
        strcat(folder,'\play_hihat_snare_on_135537.wav'); ...

        'bass', ...
        strcat(folder,'\play_bass_snare_off_134129.wav'), ...
        strcat(folder,'\play_bass_snare_off_134142.wav'), ...
        strcat(folder,'\play_bass_snare_off_134305.wav'), ...
        strcat(folder,'\play_bass_snare_off_134311.wav'), ...
        strcat(folder,'\play_bass_snare_off_134318.wav'), ...
        strcat(folder,'\play_bass_snare_off_134326.wav'), ...
        strcat(folder,'\play_bass_snare_off_134334.wav'), ...
        strcat(folder,'\play_bass_snare_off_134341.wav'), ...
        strcat(folder,'\play_bass_snare_off_134356.wav'), ...
        strcat(folder,'\play_bass_snare_off_134405.wav'); ...

        'snare', ...
        strcat(folder,'\play_snare_snare_on_134744.wav'), ...
        strcat(folder,'\play_snare_snare_on_134751.wav'), ...
        strcat(folder,'\play_snare_snare_on_134757.wav'), ...
        strcat(folder,'\play_snare_snare_on_134804.wav'), ...
        strcat(folder,'\play_snare_snare_on_134813.wav'), ...
        strcat(folder,'\play_snare_snare_on_134820.wav'), ...
        strcat(folder,'\play_snare_snare_on_134827.wav'), ...
        strcat(folder,'\play_snare_snare_on_134834.wav'), ...
        strcat(folder,'\play_snare_snare_on_134841.wav'), ...
        strcat(folder,'\play_snare_snare_on_134847.wav'); ...

        'tom 1', ...
        strcat(folder,'\play_tom1_snare_on_140147.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140205.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140212.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140218.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140224.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140232.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140238.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140245.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140257.wav'), ...
        strcat(folder,'\play_tom1_snare_on_140304.wav'); ...

        'tom 2', ...
        strcat(folder,'\play_tom2_snare_on_140434.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140442.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140449.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140455.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140502.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140509.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140515.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140521.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140527.wav'), ...
        strcat(folder,'\play_tom2_snare_on_140533.wav'); ...

        'tom 3', ...    
        strcat(folder,'\play_tom3_snare_on_140655.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140702.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140708.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140714.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140720.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140726.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140731.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140737.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140744.wav'), ...
        strcat(folder,'\play_tom3_snare_on_140750.wav');
    };

    [y,fs] = audioread(char(training_files(1,2)));
    training_data = zeros(length(y),9);
    test_data = zeros(length(y),length(training_files(:,1))*(length(training_files(:,1))-1));
    
    max_i = length(training_files(:,1));
    max_j = length(training_files(1,:));
    
    training_drums = cell(1,9);
    for i = 1:max_i   
        [y] = audioread(char(training_files(i,2)));            
        training_data(1:length(y),i) = y; 
        training_drums(i) = training_files(i,1);
    end
    
    test_drums = cell(1, 90);
    for i = 1:max_i
        for j = 2:max_j           
            loc = (i-1)*(max_j-1)+(j-1);
            test_drums(loc) = training_files(i,1);
        end
    end
    
    for i = 1:max_i
        for j = 2:max_j      
            loc = (i-1)*(max_j-1)+(j-1);
            
            [y] = audioread(char(test_files(i,j)));
            test_data(1:length(y),loc) = y;  
        end
    end
end

